insert into seat values ('A01', 'rear stalls');
insert into seat values ('A02', 'rear stalls');
insert into seat values ('A03', 'rear stalls');
insert into seat values ('A04', 'rear stalls');
insert into seat values ('A05', 'rear stalls');
insert into seat values ('A06', 'rear stalls');
insert into seat values ('A07', 'rear stalls');
insert into seat values ('A08', 'rear stalls');
insert into seat values ('A09', 'rear stalls');
insert into seat values ('A10', 'rear stalls');
insert into seat values ('A11', 'rear stalls');
insert into seat values ('A12', 'rear stalls');
insert into seat values ('A13', 'rear stalls');
insert into seat values ('A14', 'rear stalls');
insert into seat values ('A15', 'rear stalls');
insert into seat values ('A16', 'rear stalls');
insert into seat values ('A17', 'rear stalls');
insert into seat values ('A18', 'rear stalls');
insert into seat values ('A19', 'rear stalls');
insert into seat values ('A20', 'rear stalls');
insert into seat values ('B01', 'rear stalls');
insert into seat values ('B02', 'rear stalls');
insert into seat values ('B03', 'rear stalls');
insert into seat values ('B04', 'rear stalls');
insert into seat values ('B05', 'rear stalls');
insert into seat values ('B06', 'rear stalls');
insert into seat values ('B07', 'rear stalls');
insert into seat values ('B08', 'rear stalls');
insert into seat values ('B09', 'rear stalls');
insert into seat values ('B10', 'rear stalls');
insert into seat values ('B11', 'rear stalls');
insert into seat values ('B12', 'rear stalls');
insert into seat values ('B13', 'rear stalls');
insert into seat values ('B14', 'rear stalls');
insert into seat values ('B15', 'rear stalls');
insert into seat values ('B16', 'rear stalls');
insert into seat values ('B17', 'rear stalls');
insert into seat values ('B18', 'rear stalls');
insert into seat values ('B19', 'rear stalls');
insert into seat values ('B20', 'rear stalls');
insert into seat values ('C01', 'rear stalls');
insert into seat values ('C02', 'rear stalls');
insert into seat values ('C03', 'rear stalls');
insert into seat values ('C04', 'rear stalls');
insert into seat values ('C05', 'rear stalls');
insert into seat values ('C06', 'rear stalls');
insert into seat values ('C07', 'rear stalls');
insert into seat values ('C08', 'rear stalls');
insert into seat values ('C09', 'rear stalls');
insert into seat values ('C10', 'rear stalls');
insert into seat values ('C11', 'rear stalls');
insert into seat values ('C12', 'rear stalls');
insert into seat values ('C13', 'rear stalls');
insert into seat values ('C14', 'rear stalls');
insert into seat values ('C15', 'rear stalls');
insert into seat values ('C16', 'rear stalls');
insert into seat values ('C17', 'rear stalls');
insert into seat values ('C18', 'rear stalls');
insert into seat values ('C19', 'rear stalls');
insert into seat values ('C20', 'rear stalls');
insert into seat values ('D01', 'rear stalls');
insert into seat values ('D02', 'rear stalls');
insert into seat values ('D03', 'rear stalls');
insert into seat values ('D04', 'rear stalls');
insert into seat values ('D05', 'rear stalls');
insert into seat values ('D06', 'rear stalls');
insert into seat values ('D07', 'rear stalls');
insert into seat values ('D08', 'rear stalls');
insert into seat values ('D09', 'rear stalls');
insert into seat values ('D10', 'rear stalls');
insert into seat values ('D11', 'rear stalls');
insert into seat values ('D12', 'rear stalls');
insert into seat values ('D13', 'rear stalls');
insert into seat values ('D14', 'rear stalls');
insert into seat values ('D15', 'rear stalls');
insert into seat values ('D16', 'rear stalls');
insert into seat values ('D17', 'rear stalls');
insert into seat values ('D18', 'rear stalls');
insert into seat values ('D19', 'rear stalls');
insert into seat values ('D20', 'rear stalls');
insert into seat values ('E01', 'rear stalls');
insert into seat values ('E02', 'rear stalls');
insert into seat values ('E03', 'rear stalls');
insert into seat values ('E04', 'rear stalls');
insert into seat values ('E05', 'rear stalls');
insert into seat values ('E06', 'rear stalls');
insert into seat values ('E07', 'rear stalls');
insert into seat values ('E08', 'rear stalls');
insert into seat values ('E09', 'rear stalls');
insert into seat values ('E10', 'rear stalls');
insert into seat values ('E11', 'rear stalls');
insert into seat values ('E12', 'rear stalls');
insert into seat values ('E13', 'rear stalls');
insert into seat values ('E14', 'rear stalls');
insert into seat values ('E15', 'rear stalls');
insert into seat values ('E16', 'rear stalls');
insert into seat values ('E17', 'rear stalls');
insert into seat values ('E18', 'rear stalls');
insert into seat values ('E19', 'rear stalls');
insert into seat values ('E20', 'rear stalls');
insert into seat values ('F01', 'rear stalls');
insert into seat values ('F02', 'rear stalls');
insert into seat values ('F03', 'rear stalls');
insert into seat values ('F04', 'rear stalls');
insert into seat values ('F05', 'rear stalls');
insert into seat values ('F06', 'rear stalls');
insert into seat values ('F07', 'rear stalls');
insert into seat values ('F08', 'rear stalls');
insert into seat values ('F09', 'rear stalls');
insert into seat values ('F10', 'rear stalls');
insert into seat values ('F11', 'rear stalls');
insert into seat values ('F12', 'rear stalls');
insert into seat values ('F13', 'rear stalls');
insert into seat values ('F14', 'rear stalls');
insert into seat values ('F15', 'rear stalls');
insert into seat values ('F16', 'rear stalls');
insert into seat values ('F17', 'rear stalls');
insert into seat values ('F18', 'rear stalls');
insert into seat values ('F19', 'rear stalls');
insert into seat values ('F20', 'rear stalls');
insert into seat values ('G01', 'rear stalls');
insert into seat values ('G02', 'rear stalls');
insert into seat values ('G03', 'rear stalls');
insert into seat values ('G04', 'rear stalls');
insert into seat values ('G05', 'rear stalls');
insert into seat values ('G06', 'rear stalls');
insert into seat values ('G07', 'rear stalls');
insert into seat values ('G08', 'rear stalls');
insert into seat values ('G09', 'rear stalls');
insert into seat values ('G10', 'rear stalls');
insert into seat values ('G11', 'rear stalls');
insert into seat values ('G12', 'rear stalls');
insert into seat values ('G13', 'rear stalls');
insert into seat values ('G14', 'rear stalls');
insert into seat values ('G15', 'rear stalls');
insert into seat values ('G16', 'rear stalls');
insert into seat values ('G17', 'rear stalls');
insert into seat values ('G18', 'rear stalls');
insert into seat values ('G19', 'rear stalls');
insert into seat values ('G20', 'rear stalls');
insert into seat values ('H01', 'rear stalls');
insert into seat values ('H02', 'rear stalls');
insert into seat values ('H03', 'rear stalls');
insert into seat values ('H04', 'rear stalls');
insert into seat values ('H05', 'rear stalls');
insert into seat values ('H06', 'rear stalls');
insert into seat values ('H07', 'rear stalls');
insert into seat values ('H08', 'rear stalls');
insert into seat values ('H09', 'rear stalls');
insert into seat values ('H10', 'rear stalls');
insert into seat values ('H11', 'rear stalls');
insert into seat values ('H12', 'rear stalls');
insert into seat values ('H13', 'rear stalls');
insert into seat values ('H14', 'rear stalls');
insert into seat values ('H15', 'rear stalls');
insert into seat values ('H16', 'rear stalls');
insert into seat values ('H17', 'rear stalls');
insert into seat values ('H18', 'rear stalls');
insert into seat values ('H19', 'rear stalls');
insert into seat values ('H20', 'rear stalls');
insert into seat values ('I01', 'rear stalls');
insert into seat values ('I02', 'rear stalls');
insert into seat values ('I03', 'rear stalls');
insert into seat values ('I04', 'rear stalls');
insert into seat values ('I05', 'rear stalls');
insert into seat values ('I06', 'rear stalls');
insert into seat values ('I07', 'rear stalls');
insert into seat values ('I08', 'rear stalls');
insert into seat values ('I09', 'rear stalls');
insert into seat values ('I10', 'rear stalls');
insert into seat values ('I11', 'rear stalls');
insert into seat values ('I12', 'rear stalls');
insert into seat values ('I13', 'rear stalls');
insert into seat values ('I14', 'rear stalls');
insert into seat values ('I15', 'rear stalls');
insert into seat values ('I16', 'rear stalls');
insert into seat values ('I17', 'rear stalls');
insert into seat values ('I18', 'rear stalls');
insert into seat values ('I19', 'rear stalls');
insert into seat values ('I20', 'rear stalls');
insert into seat values ('J01', 'rear stalls');
insert into seat values ('J02', 'rear stalls');
insert into seat values ('J03', 'rear stalls');
insert into seat values ('J04', 'rear stalls');
insert into seat values ('J05', 'rear stalls');
insert into seat values ('J06', 'rear stalls');
insert into seat values ('J07', 'rear stalls');
insert into seat values ('J08', 'rear stalls');
insert into seat values ('J09', 'rear stalls');
insert into seat values ('J10', 'rear stalls');
insert into seat values ('J11', 'rear stalls');
insert into seat values ('J12', 'rear stalls');
insert into seat values ('J13', 'rear stalls');
insert into seat values ('J14', 'rear stalls');
insert into seat values ('J15', 'rear stalls');
insert into seat values ('J16', 'rear stalls');
insert into seat values ('J17', 'rear stalls');
insert into seat values ('J18', 'rear stalls');
insert into seat values ('J19', 'rear stalls');
insert into seat values ('J20', 'rear stalls');
insert into seat values ('K01', 'front stalls');
insert into seat values ('K02', 'front stalls');
insert into seat values ('K03', 'front stalls');
insert into seat values ('K04', 'front stalls');
insert into seat values ('K05', 'front stalls');
insert into seat values ('K06', 'front stalls');
insert into seat values ('K07', 'front stalls');
insert into seat values ('K08', 'front stalls');
insert into seat values ('K09', 'front stalls');
insert into seat values ('K10', 'front stalls');
insert into seat values ('K11', 'front stalls');
insert into seat values ('K12', 'front stalls');
insert into seat values ('K13', 'front stalls');
insert into seat values ('K14', 'front stalls');
insert into seat values ('K15', 'front stalls');
insert into seat values ('K16', 'front stalls');
insert into seat values ('K17', 'front stalls');
insert into seat values ('K18', 'front stalls');
insert into seat values ('K19', 'front stalls');
insert into seat values ('K20', 'front stalls');
insert into seat values ('L01', 'front stalls');
insert into seat values ('L02', 'front stalls');
insert into seat values ('L03', 'front stalls');
insert into seat values ('L04', 'front stalls');
insert into seat values ('L05', 'front stalls');
insert into seat values ('L06', 'front stalls');
insert into seat values ('L07', 'front stalls');
insert into seat values ('L08', 'front stalls');
insert into seat values ('L09', 'front stalls');
insert into seat values ('L10', 'front stalls');
insert into seat values ('L11', 'front stalls');
insert into seat values ('L12', 'front stalls');
insert into seat values ('L13', 'front stalls');
insert into seat values ('L14', 'front stalls');
insert into seat values ('L15', 'front stalls');
insert into seat values ('L16', 'front stalls');
insert into seat values ('L17', 'front stalls');
insert into seat values ('L18', 'front stalls');
insert into seat values ('L19', 'front stalls');
insert into seat values ('L20', 'front stalls');
insert into seat values ('M01', 'front stalls');
insert into seat values ('M02', 'front stalls');
insert into seat values ('M03', 'front stalls');
insert into seat values ('M04', 'front stalls');
insert into seat values ('M05', 'front stalls');
insert into seat values ('M06', 'front stalls');
insert into seat values ('M07', 'front stalls');
insert into seat values ('M08', 'front stalls');
insert into seat values ('M09', 'front stalls');
insert into seat values ('M10', 'front stalls');
insert into seat values ('M11', 'front stalls');
insert into seat values ('M12', 'front stalls');
insert into seat values ('M13', 'front stalls');
insert into seat values ('M14', 'front stalls');
insert into seat values ('M15', 'front stalls');
insert into seat values ('M16', 'front stalls');
insert into seat values ('M17', 'front stalls');
insert into seat values ('M18', 'front stalls');
insert into seat values ('M19', 'front stalls');
insert into seat values ('M20', 'front stalls');
insert into seat values ('N01', 'front stalls');
insert into seat values ('N02', 'front stalls');
insert into seat values ('N03', 'front stalls');
insert into seat values ('N04', 'front stalls');
insert into seat values ('N05', 'front stalls');
insert into seat values ('N06', 'front stalls');
insert into seat values ('N07', 'front stalls');
insert into seat values ('N08', 'front stalls');
insert into seat values ('N09', 'front stalls');
insert into seat values ('N10', 'front stalls');
insert into seat values ('N11', 'front stalls');
insert into seat values ('N12', 'front stalls');
insert into seat values ('N13', 'front stalls');
insert into seat values ('N14', 'front stalls');
insert into seat values ('N15', 'front stalls');
insert into seat values ('N16', 'front stalls');
insert into seat values ('N17', 'front stalls');
insert into seat values ('N18', 'front stalls');
insert into seat values ('N19', 'front stalls');
insert into seat values ('N20', 'front stalls');
insert into seat values ('O01', 'front stalls');
insert into seat values ('O02', 'front stalls');
insert into seat values ('O03', 'front stalls');
insert into seat values ('O04', 'front stalls');
insert into seat values ('O05', 'front stalls');
insert into seat values ('O06', 'front stalls');
insert into seat values ('O07', 'front stalls');
insert into seat values ('O08', 'front stalls');
insert into seat values ('O09', 'front stalls');
insert into seat values ('O10', 'front stalls');
insert into seat values ('O11', 'front stalls');
insert into seat values ('O12', 'front stalls');
insert into seat values ('O13', 'front stalls');
insert into seat values ('O14', 'front stalls');
insert into seat values ('O15', 'front stalls');
insert into seat values ('O16', 'front stalls');
insert into seat values ('O17', 'front stalls');
insert into seat values ('O18', 'front stalls');
insert into seat values ('O19', 'front stalls');
insert into seat values ('O20', 'front stalls');
insert into seat values ('P01', 'front stalls');
insert into seat values ('P02', 'front stalls');
insert into seat values ('P03', 'front stalls');
insert into seat values ('P04', 'front stalls');
insert into seat values ('P05', 'front stalls');
insert into seat values ('P06', 'front stalls');
insert into seat values ('P07', 'front stalls');
insert into seat values ('P08', 'front stalls');
insert into seat values ('P09', 'front stalls');
insert into seat values ('P10', 'front stalls');
insert into seat values ('P11', 'front stalls');
insert into seat values ('P12', 'front stalls');
insert into seat values ('P13', 'front stalls');
insert into seat values ('P14', 'front stalls');
insert into seat values ('P15', 'front stalls');
insert into seat values ('P16', 'front stalls');
insert into seat values ('P17', 'front stalls');
insert into seat values ('P18', 'front stalls');
insert into seat values ('P19', 'front stalls');
insert into seat values ('P20', 'front stalls');
insert into seat values ('Q01', 'front stalls');
insert into seat values ('Q02', 'front stalls');
insert into seat values ('Q03', 'front stalls');
insert into seat values ('Q04', 'front stalls');
insert into seat values ('Q05', 'front stalls');
insert into seat values ('Q06', 'front stalls');
insert into seat values ('Q07', 'front stalls');
insert into seat values ('Q08', 'front stalls');
insert into seat values ('Q09', 'front stalls');
insert into seat values ('Q10', 'front stalls');
insert into seat values ('Q11', 'front stalls');
insert into seat values ('Q12', 'front stalls');
insert into seat values ('Q13', 'front stalls');
insert into seat values ('Q14', 'front stalls');
insert into seat values ('Q15', 'front stalls');
insert into seat values ('Q16', 'front stalls');
insert into seat values ('Q17', 'front stalls');
insert into seat values ('Q18', 'front stalls');
insert into seat values ('Q19', 'front stalls');
insert into seat values ('Q20', 'front stalls');
insert into seat values ('R01', 'front stalls');
insert into seat values ('R02', 'front stalls');
insert into seat values ('R03', 'front stalls');
insert into seat values ('R04', 'front stalls');
insert into seat values ('R05', 'front stalls');
insert into seat values ('R06', 'front stalls');
insert into seat values ('R07', 'front stalls');
insert into seat values ('R08', 'front stalls');
insert into seat values ('R09', 'front stalls');
insert into seat values ('R10', 'front stalls');
insert into seat values ('R11', 'front stalls');
insert into seat values ('R12', 'front stalls');
insert into seat values ('R13', 'front stalls');
insert into seat values ('R14', 'front stalls');
insert into seat values ('R15', 'front stalls');
insert into seat values ('R16', 'front stalls');
insert into seat values ('R17', 'front stalls');
insert into seat values ('R18', 'front stalls');
insert into seat values ('R19', 'front stalls');
insert into seat values ('R20', 'front stalls');
insert into seat values ('S01', 'front stalls');
insert into seat values ('S02', 'front stalls');
insert into seat values ('S03', 'front stalls');
insert into seat values ('S04', 'front stalls');
insert into seat values ('S05', 'front stalls');
insert into seat values ('S06', 'front stalls');
insert into seat values ('S07', 'front stalls');
insert into seat values ('S08', 'front stalls');
insert into seat values ('S09', 'front stalls');
insert into seat values ('S10', 'front stalls');
insert into seat values ('S11', 'front stalls');
insert into seat values ('S12', 'front stalls');
insert into seat values ('S13', 'front stalls');
insert into seat values ('S14', 'front stalls');
insert into seat values ('S15', 'front stalls');
insert into seat values ('S16', 'front stalls');
insert into seat values ('S17', 'front stalls');
insert into seat values ('S18', 'front stalls');
insert into seat values ('S19', 'front stalls');
insert into seat values ('S20', 'front stalls');
insert into seat values ('T01', 'front stalls');
insert into seat values ('T02', 'front stalls');
insert into seat values ('T03', 'front stalls');
insert into seat values ('T04', 'front stalls');
insert into seat values ('T05', 'front stalls');
insert into seat values ('T06', 'front stalls');
insert into seat values ('T07', 'front stalls');
insert into seat values ('T08', 'front stalls');
insert into seat values ('T09', 'front stalls');
insert into seat values ('T10', 'front stalls');
insert into seat values ('T11', 'front stalls');
insert into seat values ('T12', 'front stalls');
insert into seat values ('T13', 'front stalls');
insert into seat values ('T14', 'front stalls');
insert into seat values ('T15', 'front stalls');
insert into seat values ('T16', 'front stalls');
insert into seat values ('T17', 'front stalls');
insert into seat values ('T18', 'front stalls');
insert into seat values ('T19', 'front stalls');
insert into seat values ('T20', 'front stalls');
insert into seat values ('U01', 'balcony');
insert into seat values ('U02', 'balcony');
insert into seat values ('U03', 'balcony');
insert into seat values ('U04', 'balcony');
insert into seat values ('U05', 'balcony');
insert into seat values ('U06', 'balcony');
insert into seat values ('U07', 'balcony');
insert into seat values ('U08', 'balcony');
insert into seat values ('U09', 'balcony');
insert into seat values ('U10', 'balcony');
insert into seat values ('U11', 'balcony');
insert into seat values ('U12', 'balcony');
insert into seat values ('U13', 'balcony');
insert into seat values ('U14', 'balcony');
insert into seat values ('U15', 'balcony');
insert into seat values ('U16', 'balcony');
insert into seat values ('U17', 'balcony');
insert into seat values ('U18', 'balcony');
insert into seat values ('U19', 'balcony');
insert into seat values ('U20', 'balcony');
insert into seat values ('V01', 'balcony');
insert into seat values ('V02', 'balcony');
insert into seat values ('V03', 'balcony');
insert into seat values ('V04', 'balcony');
insert into seat values ('V05', 'balcony');
insert into seat values ('V06', 'balcony');
insert into seat values ('V07', 'balcony');
insert into seat values ('V08', 'balcony');
insert into seat values ('V09', 'balcony');
insert into seat values ('V10', 'balcony');
insert into seat values ('V11', 'balcony');
insert into seat values ('V12', 'balcony');
insert into seat values ('V13', 'balcony');
insert into seat values ('V14', 'balcony');
insert into seat values ('V15', 'balcony');
insert into seat values ('V16', 'balcony');
insert into seat values ('V17', 'balcony');
insert into seat values ('V18', 'balcony');
insert into seat values ('V19', 'balcony');
insert into seat values ('V20', 'balcony');
insert into seat values ('W01', 'balcony');
insert into seat values ('W02', 'balcony');
insert into seat values ('W03', 'balcony');
insert into seat values ('W04', 'balcony');
insert into seat values ('W05', 'balcony');
insert into seat values ('W06', 'balcony');
insert into seat values ('W07', 'balcony');
insert into seat values ('W08', 'balcony');
insert into seat values ('W09', 'balcony');
insert into seat values ('W10', 'balcony');
insert into seat values ('W11', 'balcony');
insert into seat values ('W12', 'balcony');
insert into seat values ('W13', 'balcony');
insert into seat values ('W14', 'balcony');
insert into seat values ('W15', 'balcony');
insert into seat values ('W16', 'balcony');
insert into seat values ('W17', 'balcony');
insert into seat values ('W18', 'balcony');
insert into seat values ('W19', 'balcony');
insert into seat values ('W20', 'balcony');
insert into seat values ('X01', 'balcony');
insert into seat values ('X02', 'balcony');
insert into seat values ('X03', 'balcony');
insert into seat values ('X04', 'balcony');
insert into seat values ('X05', 'balcony');
insert into seat values ('X06', 'balcony');
insert into seat values ('X07', 'balcony');
insert into seat values ('X08', 'balcony');
insert into seat values ('X09', 'balcony');
insert into seat values ('X10', 'balcony');
insert into seat values ('X11', 'balcony');
insert into seat values ('X12', 'balcony');
insert into seat values ('X13', 'balcony');
insert into seat values ('X14', 'balcony');
insert into seat values ('X15', 'balcony');
insert into seat values ('X16', 'balcony');
insert into seat values ('X17', 'balcony');
insert into seat values ('X18', 'balcony');
insert into seat values ('X19', 'balcony');
insert into seat values ('X20', 'balcony');
insert into seat values ('Y01', 'balcony');
insert into seat values ('Y02', 'balcony');
insert into seat values ('Y03', 'balcony');
insert into seat values ('Y04', 'balcony');
insert into seat values ('Y05', 'balcony');
insert into seat values ('Y06', 'balcony');
insert into seat values ('Y07', 'balcony');
insert into seat values ('Y08', 'balcony');
insert into seat values ('Y09', 'balcony');
insert into seat values ('Y10', 'balcony');
insert into seat values ('Y11', 'balcony');
insert into seat values ('Y12', 'balcony');
insert into seat values ('Y13', 'balcony');
insert into seat values ('Y14', 'balcony');
insert into seat values ('Y15', 'balcony');
insert into seat values ('Y16', 'balcony');
insert into seat values ('Y17', 'balcony');
insert into seat values ('Y18', 'balcony');
insert into seat values ('Y19', 'balcony');
insert into seat values ('Y20', 'balcony');
insert into seat values ('Z01', 'box 1');
insert into seat values ('Z02', 'box 1');
insert into seat values ('Z03', 'box 1');
insert into seat values ('Z04', 'box 1');
insert into seat values ('Z05', 'box 2');
insert into seat values ('Z06', 'box 2');
insert into seat values ('Z07', 'box 2');
insert into seat values ('Z08', 'box 2');
insert into seat values ('Z09', 'box 3');
insert into seat values ('Z10', 'box 3');
insert into seat values ('Z11', 'box 3');
insert into seat values ('Z12', 'box 3');
insert into seat values ('Z13', 'box 3');
insert into seat values ('Z14', 'box 3');
insert into seat values ('Z15', 'box 4');
insert into seat values ('Z16', 'box 4');
insert into seat values ('Z17', 'box 4');
insert into seat values ('Z18', 'box 4');
insert into seat values ('Z19', 'box 4');
insert into seat values ('Z20', 'box 4');